--Explore all objects in the database	
select * from INFORMATION_SCHEMA.TABLES


--Explore all columns in the database
select * from INFORMATION_SCHEMA.COLUMNS

--Explore all countries where our customers are coming from 
select distinct country from gold.dim_customers

--Explore all categories "The major Divisions"
select distinct category_name from gold.dim_products

--Explore all categories "The major Divisions"
select distinct category_name,subcategory,product_name from gold.dim_products order by 1,2,3

--Find the first and last order dates
--How many years of sales are available in months
select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(month,min(order_date),max(order_date)) as order_range_months
from gold.fact_sales

-- Find the youngest and the oldest customer
select
min(birthdate) as oldest_customer_birthdate,
datediff(year,min(birthdate),getdate()) as oldest_customer_age,
max(birthdate) as youngest_customer_birthdate,
datediff(year,max(birthdate),getdate()) as youngest_customer_age
from gold.dim_customers

--Find the Total sales
select sum(sales_amount) as total_sales from gold.fact_sales
--Find how many items are sold
select sum(quantity) as number_of_items_sold from gold.fact_sales
--Find the average selling price
select avg(price) as average_selling_price from gold.fact_sales
--Find the total number of orders 
select count( distinct order_number) as total_orders from gold.fact_sales
--Find the total number of products
select count(distinct product_name) as total_number_of_products from gold.dim_products
-- Find the total number of customers
select count(distinct customer_key) as total_customers from gold.dim_customers
--Find the total number of customers that have placed an order
select count(distinct customer_key) as total_customers_who_ordered from gold.fact_sales 

--Generate a report that shows all key metrics of the business 
select 'total_sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union 
select  'total_quantity' as measure_name,sum(quantity) as measure_value from gold.fact_sales
union 
select 'average_price' as measure_name, avg(price) as measure_value from gold.fact_sales
union
select 'total_orders' as measure_name,count( distinct order_number) as measure_value from gold.fact_sales
union
select 'total_number_of_products' as measure_name,count(distinct product_name) as measure_value  from gold.dim_products
union
select 'total_customers' as measure_name,count(distinct customer_key) as measure_value from gold.dim_customers
union
select 'total_customers_who_ordered' as measure_name,count(distinct customer_key) as measure_value from gold.fact_sales

-- Find total customers by countries 
select country,count(customer_key) as total_customers
from gold.dim_customers 
group by country 
order by count(customer_key) desc

--Find total customers by gender
select 
gender,
count(customer_key) as total_customers
from gold.dim_customers 
group by gender  
order by count(customer_key) desc

--Find total products by category
select category_name,count(distinct product_id) as total_products from gold.dim_products group by category_name  order by count(distinct product_id)

--What is the average cost in each category 
select category_name,AVG(cost)as average_cost from gold.dim_products  group by category_name order by AVG(cost) desc

--What is the total revenue generated for each category		
select 
category_name,
sum(sales_amount)as total_revenue
from gold.fact_sales as fs 
left join 
gold.dim_products as dp 
on fs.product_key=dp.product_key 
group by category_name 
order by sum(price) desc

--What is the total revenue generated by each customer
select 
concat(first_name,' ',last_name)as full_name ,
sum(sales_amount) as total_revenue 
from gold.fact_sales as fs left join gold.dim_customers as dc on fs.customer_key=dc.customer_key 
group by concat(first_name,' ',last_name) 
order by sum(sales_amount) desc

--What is the distribution of sold items across countries?
select 
country ,
sum(quantity) as total_items 
from gold.fact_sales as fs left join gold.dim_customers as dc on fs.customer_key=dc.customer_key 
group by country
order by sum(quantity) desc

-- which 5 products generate the highest revenue
select * from
(
select
product_name,
sum(sales_amount)as total_revenue,
ROW_NUMBER() over(order by sum(sales_amount)desc) as rank_products
from gold.fact_sales as fs 
left join 
gold.dim_products as dp 
on fs.product_key=dp.product_key 
group by product_name )t
where rank_products<=5

--what are the 5 worst-performing products in terms of sales? 
select * from
(
select
product_name,
sum(sales_amount)as total_revenue,
ROW_NUMBER() over(order by sum(sales_amount)) as rank_products
from gold.fact_sales as fs 
left join 
gold.dim_products as dp 
on fs.product_key=dp.product_key 
group by product_name )t
where rank_products<=5

--Find the top 10 customers who have generated the highest revenue

select * from
(
select
concat(first_name,' ',last_name)as full_name,
sum(sales_amount)as total_revenue,
ROW_NUMBER() over(order by sum(sales_amount)desc) as rank_customers
from gold.fact_sales as fs 
left join gold.dim_customers as dc on fs.customer_key=dc.customer_key 
group by concat(first_name,' ',last_name) )t
where rank_customers<=10


--Find 3 customers with the fewest orders placed 
select * from
(
select
concat(first_name,' ',last_name)as full_name,
count(distinct order_number)as total_orders,
ROW_NUMBER() over(order by count(distinct order_number)) as rank_customers
from gold.fact_sales as fs 
left join gold.dim_customers as dc on fs.customer_key=dc.customer_key 
group by concat(first_name,' ',last_name) )t
where rank_customers<=10

